version: "3.9"

services:
  flask_app:
    image: barradas13/judge
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PROBLEMS_JSON_B64=${PROBLEMS_JSON_B64}
      - JUDGE_URL=${JUDGE_URL}
      - JUDGE0_KEY=${JUDGE0_KEY}
      - PORT=${PORT}
